---
apiVersion: v1
stringData:
  CLOUD_HSM_IP: "${HSM_IP}"
  CUSTOMER_CA: "${CA_CONTENTS}"
  VAULT_ENT_LICENSE: "${hsm_license_key}"
kind: Secret
metadata:
  name: vault-config-secrets
  namespace: vault
type: Opaque

---
apiVersion: v1
stringData:
  AWS_ACCESS_KEY_ID: "${AUTOMATION_USER_AWS_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${AUTOMATION_USER_AWS_SECRET_KEY}"
kind: Secret
metadata:
  name: vault-eks-creds
  namespace: vault
type: Opaque