global:
  imagePullSecrets:
    - name: vault-docker-secret

server:
  image:
    repository: sifchain/vault
    pullPolicy: Always
    tag: "1.2.7"

  agentImage:
    repository: sifchain/vault
    tag: "1.2.7"
    pullPolicy: Always

  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-eks-creds
      secretKey: AWS_ACCESS_KEY_ID

    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-eks-creds
      secretKey: AWS_SECRET_ACCESS_KEY

    - envName: CLOUD_HSM_IP
      secretName: vault-config-secrets
      secretKey: CLOUD_HSM_IP

    - envName: CUSTOMER_CA
      secretName: vault-config-secrets
      secretKey: CUSTOMER_CA

    - envName: VAULT_ENT_LICENSE
      secretName: vault-config-secrets
      secretKey: VAULT_ENT_LICENSE

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

    limits:
      memory: 512Mi
      cpu: 500m

  extraVolumes:
    - type: secret
      name: vault-eks-creds

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204&perfstandbyok=true"
    initialDelaySeconds: 100

  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&perfstandbyok=true"
    initialDelaySeconds: 100

  auditStorage:
    enabled: true

  dataStorage:
    enabled: true

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true

      config: |
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "http://vault-0.vault-internal.vault:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-1.vault-internal.vault:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-2.vault-internal.vault:8200"
          }
        }

        seal "pkcs11" {
          lib            = "/opt/cloudhsm/lib/libcloudhsm_pkcs11.so"
          slot           = "1"
          pin            = "-=HSM_USER=-:-=HSM_PASSWORD=-"
          generate_key   = "true"
          key_label      = "vault"
          hmac_key_label = "vault"
        }

        #disable_mlock    = "False"
        ui               = "True"

        service_registration "kubernetes" {
          namespace      = "vault"
          pod_name       = "vault"
        }

ui:
  enabled: true
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  activeVaultPodOnly: true