version: '3'

services:
  sifnode0:
    image: sifchain/sifnode:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: sifnode0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR0}
    volumes:
      - ./sifnode/root/scripts:/root/scripts:Z
    command: /root/scripts/sifnode.sh
    networks:
      sifchain:
        ipv4_address: ${IPADDR0}

  sifnode1:
    image: sifchain/sifnode:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: sifnode1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR1}
    volumes:
      - ./sifnode/root/scripts:/root/scripts:Z
    command: /root/scripts/sifnode.sh
    networks:
      sifchain:
        ipv4_address: ${IPADDR1}

  ts-relayer:
    image: sifchain/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      SIFNODE0_MNEMONIC: ${MNEMONIC}
      SIFNODE1_MNEMONIC: ${MNEMONIC}
      RPC0: ${IPADDR0}:26657
      RPC1: ${IPADDR1}:26657
      PREFIX0: sif
      PREFIX1: sif
      GAS_PRICE0: "0.5rowan"
      GAS_PRICE1: "0.5rowan"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - sifnode0
      - sifnode1
    command: /root/scripts/ts-relayer.sh
    networks:
      sifchain:
        ipv4_address: ${IPADDR2}

networks:
  sifchain:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
