version: '3'

services:
  sifnode0:
    image: sifchain/sifnoded:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: sifnode0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: 192.168.65.2
    volumes:
      - ./sifnode/root/scripts:/root/scripts:Z
    command: /root/scripts/sifnode.sh
    networks:
      sifchain:
        ipv4_address: 192.168.65.2

  sifnode1:
    image: sifchain/sifnoded:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: sifnode1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: 192.168.65.3
    volumes:
      - ./sifnode/root/scripts:/root/scripts:Z
    command: /root/scripts/sifnode.sh
    networks:
      sifchain:
        ipv4_address: 192.168.65.3

  ts-relayer:
    image: sifchain/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      SIFNODE0_MNEMONIC: ${MNEMONIC}
      SIFNODE1_MNEMONIC: ${MNEMONIC}
      RPC0: "192.168.65.2:26657"
      RPC1: "192.168.65.3:26657"
      PREFIX0: sif
      PREFIX1: ${PREFIX0}
      GAS_PRICE0: "0.5rowan"
      GAS_PRICE1: "0.5rowan"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - sifnode0
      - sifnode1
    command: /root/scripts/ts-relayer.sh
    networks:
      sifchain:
        ipv4_address: 192.168.65.4

networks:
  sifchain:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.65.1/24
