apiVersion: v1
kind: Service
metadata:
  name: {{ template "geth.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.http.port }}
      targetPort: rpc
    - name: ws
      port: {{ .Values.ws.port }}
      targetPort: ws
    - name: proxy-rpc
      port: {{ .Values.proxy.http.port }}
      targetPort: proxy-rpc
    - name: proxy-ws
      port: {{ .Values.proxy.ws.port }}
      targetPort: proxy-ws
  selector:
    app: {{ template "geth.name" . }}
    release: {{ .Release.Name }}