name: Cert-Manager Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: devnet, testnet
        required: true

jobs:
  #deploy cert-manager to us devnet environment
  deploy_devnet_certmanager_us:
    name: deploy-certmanager-devnet-us
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "us-east-1"
      aws_cluster_name: "sifchain-aws-devnet-us"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "devnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "devnet"
      app_region: "us"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'devnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File...."
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config

  #deploy cert-manager to eu devnet environment
  deploy_devnet_certmanager_eu:
    name: deploy-certmanager-devnet-eu
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "eu-west-1"
      aws_cluster_name: "sifchain-aws-devnet-eu"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "devnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "devnet"
      app_region: "eu"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'devnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config

  #deploy cert-manager to sg devnet environment
  deploy_devnet_certmanager_sg:
    name: deploy-certmanager-devnet-sg
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "ap-southeast-1"
      aws_cluster_name: "sifchain-aws-devnet-sg"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "devnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "devnet"
      app_region: "sg"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'devnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated...."
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config


  #deploy cert-manager to au devnet environment
  deploy_devnet_certmanager_au:
    name: deploy-certmanager-devnet-au
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "ap-southeast-2"
      aws_cluster_name: "sifchain-aws-devnet-au"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "devnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "devnet"
      app_region: "au"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'devnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config




  #deploy cert-manager to us testnet environment
  deploy_testnet_certmanager_us:
    name: deploy-certmanager-testnet-us
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "us-east-1"
      aws_cluster_name: "sifchain-aws-testnet-us"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "testnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "testnet"
      app_region: "us"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'testnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File..."
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config

  #deploy cert-manager to eu testnet environment
  deploy_testnet_certmanager_eu:
    name: deploy-certmanager-testnet-eu
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "eu-west-1"
      aws_cluster_name: "sifchain-aws-testnet-eu"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "testnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "testnet"
      app_region: "eu"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'testnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config

  #deploy cert-manager to sg testnet environment
  deploy_testnet_certmanager_sg:
    name: deploy-certmanager-testnet-sg
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "ap-southeast-1"
      aws_cluster_name: "sifchain-aws-testnet-sg"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "testnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "testnet"
      app_region: "sg"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'testnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated...."
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config


  #deploy cert-manager to au testnet environment
  deploy_testnet_certmanager_au:
    name: deploy-certmanager-testnet-au
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "ap-southeast-2"
      aws_cluster_name: "sifchain-aws-testnet-au"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      env: "testnet"
      app_namespace: "cert-manager"
      app_name: "cert-manager"
      app_env: "testnet"
      app_region: "au"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'testnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Rake
        run: gem install rake

      - name: Sifchain Art
        shell: bash
        run: |
          rake "cluster:generate:art[]"

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File"
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Install Cert-Manager
        shell: bash
        run: |
          set +x
          echo "Install Cert-Manager"
          rake "cluster:certmanager:install[]"

      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config
