name: Deploy EBRELAYER Swingset

on:
  push:
    branches:
      - 'ebrelayer-pipeline-development'

jobs:
  build:
    name: deploy-ebrelayer
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup AWS Profile
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          export PATH=$(pwd):${PATH}
          mkdir -p ~/.aws
          touch ~/.aws/config
          echo "[profile swing-set]" > ~/.aws/config
          echo "role_arn = arn:aws:iam::983740309645:role/OrganizationAccountAccessRole" >> ~/.aws/config
          echo "color = 83000a" >> ~/.aws/config
          echo "role_session_name = elk_stack" >> ~/.aws/config
          echo "region = ap-southeast-2" >> ~/.aws/config

      - name: Install dependencies
        run: gem install rake

      - name: Deploy ebrelayer on Swing-Set
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          KUBECONFIG: ${{ secrets.KUBECONFIG_SWINGSET_US }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_PROFILE: "swing-set"
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export app_namespace=ebrelayer
          export image=sifchain/ebrelayer
          export image_tag=testnet-genesis
          export env=swing-set
          export app_name=ebrelayer
          printenv
          ls -lah $(pwd)
          pwd
          echo "======"
          rake "cluster:vault:login[]"
          #rake "cluster:vault:createpolicy[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"
          #rake "cluster:vault:enablekubernetes[]"
          #rake "cluster:vault:configureapplication[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"
          #rake "cluster:vault:deploy[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"


