name: Deploy EBRELAYER Swingset

on:
  push:
    branches:
      - 'ebrelayer-pipeline-development'

jobs:
  build:
    name: deploy-ebrelayer
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup AWS Profile
        shell: bash
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          KUBECONFIG: ${{ secrets.KUBECONFIG_SWINGSET_US }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          curl -s -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          export PATH=$(pwd):${PATH}
          mkdir -p ~/.aws

          echo "[sifchain-base]" > ~/.aws/credentials
          echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region = us-west-2" >> ~/.aws/credentials

          echo "[profile swing-set]" > ~/.aws/config
          echo "source_profile = sifchain-base" >> ~/.aws/config
          echo "role_arn = arn:aws:iam::983740309645:role/OrganizationAccountAccessRole" >> ~/.aws/config
          echo "color = 83000a" >> ~/.aws/config
          echo "role_session_name = elk_stack" >> ~/.aws/config
          echo "region = ap-southeast-2" >> ~/.aws/config

          aws eks update-kubeconfig --name sifchain-aws-swing-set-us --region us-west-2 --profile swing-set --kubeconfig ./kubeconfig

      - name: Install Rake
        run: gem install rake

      - name: Login to Vault on Swing-Set
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          rake "cluster:vault:login[]"

      - name: Setup Vault Policy on Swing-Set
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          app_namespace: "ebrelayer"
          image: "sifchain/ebrelayer"
          image_tag: "testnet-genesis"
          env: "swing-set"
          app_name: "ebrelayer"
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          rake "cluster:vault:createpolicy[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"

      - name: Enable Kubernetes Vault Communication If Not Enabled
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          rake "cluster:vault:enablekubernetes[]"

      - name: Configure Vault to Mount Secrets To Application
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          app_namespace: "ebrelayer"
          image: "sifchain/ebrelayer"
          image_tag: "testnet-genesis"
          env: "swing-set"
          app_name: "ebrelayer"
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          rake "cluster:vault:configureapplication[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"

      - name: Anchore Image Scan
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          app_namespace: "ebrelayer"
          image: "sifchain/ebrelayer"
          image_tag: "testnet-genesis"
          env: "swing-set"
          app_name: "ebrelayer"
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -f -d cmd/ebrelayer/Dockerfile -p "${image}:${image_tag}"

      - name: Deploy Ebrelayer to Kubernetes Via Helm.
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN_SWINGSET_US }}
          app_namespace: "ebrelayer"
          image: "sifchain/ebrelayer"
          image_tag: "testnet-genesis"
          env: "swing-set"
          app_name: "ebrelayer"
        shell: bash
        if: github.ref == 'refs/heads/ebrelayer-pipeline-development'
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "======"
          rake "cluster:vault:deploy[${app_namespace}, ${image}, ${image_tag}, ${env}, ${app_name}]"