name: ebrelayer Interation Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: devnet, testnet
        required: true
      docker_image_tag:
        description: devnet-version, testnet-version
        required: true
  push:
    branches:
      - 'ebrelayer-pipeline-development'

jobs:
  #US DEVNET DEPLOYMENT
  deploy_devnet_ebrelayer_us:
    name: deploy-ebrelayer-devnet-us
    runs-on: ${{ matrix.os }}
    env:
      aws_region: "us-east-1"
      aws_cluster_name: "sifchain-aws-devnet-us"
      aws_role: "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole"
      VAULT_TEST_SETTINGS_PATH: "kv-v2/us/devnet/ebrelayer-smoke-test"
      app_namespace: "ebrelayer"
      image: "sifchain/ebrelayer"
      image_tag: "${{ github.event.inputs.docker_image_tag }}"
      env: "devnet"
      app_name: "ebrelayer"
      app_env: "devnet"
      app_region: "us"

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.3 ]

    if: github.event.inputs.environment == 'devnet'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Rake
        run: gem install rake
      - name: Sifchain Art
        shell: bash
        run: |
          set +x
          echo '                       iiii     ffffffffffffffff                 hhhhhhh                                 iiii'
          echo '                      i::::i   f::::::::::::::::f                h:::::h                                i::::i'
          echo '                       iiii   f::::::::::::::::::f               h:::::h                                 iiii'
          echo '                              f::::::fffffff:::::f               h:::::h'
          echo '        ssssssssss   iiiiiii  f:::::f       ffffffcccccccccccccccch::::h hhhhh         aaaaaaaaaaaaa   iiiiiiinnnn  nnnnnnnn'
          echo '      ss::::::::::s  i:::::i  f:::::f           cc:::::::::::::::ch::::hh:::::hhh      a::::::::::::a  i:::::in:::nn::::::::nn'
          echo '    ss:::::::::::::s  i::::i f:::::::ffffff    c:::::::::::::::::ch::::::::::::::hh    aaaaaaaaa:::::a  i::::in::::::::::::::nn'
          echo '    s::::::ssss:::::s i::::i f::::::::::::f   c:::::::cccccc:::::ch:::::::hhh::::::h            a::::a  i::::inn:::::::::::::::n'
          echo '     s:::::s  ssssss  i::::i f::::::::::::f   c::::::c     ccccccch::::::h   h::::::h    aaaaaaa:::::a  i::::i  n:::::nnnn:::::n'
          echo '       s::::::s       i::::i f:::::::ffffff   c:::::c             h:::::h     h:::::h  aa::::::::::::a  i::::i  n::::n    n::::n'
          echo '          s::::::s    i::::i  f:::::f         c:::::c             h:::::h     h:::::h a::::aaaa::::::a  i::::i  n::::n    n::::n'
          echo '    ssssss   s:::::s  i::::i  f:::::f         c::::::c     ccccccch:::::h     h:::::ha::::a    a:::::a  i::::i  n::::n    n::::n'
          echo '    s:::::ssss::::::si::::::if:::::::f        c:::::::cccccc:::::ch:::::h     h:::::ha::::a    a:::::a i::::::i n::::n    n::::n'
          echo '    s::::::::::::::s i::::::if:::::::f         c:::::::::::::::::ch:::::h     h:::::ha:::::aaaa::::::a i::::::i n::::n    n::::n'
          echo '     s:::::::::::ss  i::::::if:::::::f          cc:::::::::::::::ch:::::h     h:::::h a::::::::::aa:::ai::::::i n::::n    n::::n'
          echo '      sssssssssss    iiiiiiiifffffffff            cccccccccccccccchhhhhhh     hhhhhhh  aaaaaaaaaa  aaaaiiiiiiii nnnnnn    nnnnnn'

      - name: Setup AWS Profile and KUBECONFIG
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x
          echo "Configure AWSCLI Profile and Credentials from Git Secrets and Pull Temp Kubernetes Config File."
          rake "cluster:automation:configure_aws_kube_profile[${app_env}, ${AWS_ACCESS_KEY_ID}, ${AWS_SECRET_ACCESS_KEY}, ${aws_region}, ${aws_role}, ${aws_cluster_name}]"

      - name: Setup Helm Values with Variable Details
        shell: bash
        run: |
          set +x
          export PATH=$(pwd):${PATH}
          echo "This will source the vaulte secrets as environment variables defined at the path and execute the tests accordingly."
          rake "cluster:vault:generate_vault_tmp_var_source_file[${VAULT_TEST_SETTINGS_PATH}]"
          source ./tmp_secrets
          mkdir -p /home/runner/workspace/prsifnode
          mkdir -p /home/runner/workspace/prsifnode/smart-contracts/
          mkdir -p /home/runner/workspace/prsifnode/test/
          mkdir -p /home/runner/workspace/prsifnode/test/integration
          cp -r test/integration/* /home/runner/workspace/prsifnode/test/integration
          cp -r smart-contracts/* /home/runner/workspace/prsifnode/smart-contracts/
          bash /home/runner/workspace/prsifnode/test/integration/environment_setup.sh
          echo "Skiping test until echo output that shows values is removed and I get the files needed to execute the test"


      - name: Clean Temp Files and Secrets
        shell: bash
        run: |
          set +x
          echo "Clean up all temporary files that were generated"
          rm -rf ./kubeconfig
          rm -rf ~/.aws/credentials
          rm -rf ~/.aws/config
          rm -rf ./tmp_secrewts
          rm -rf ./pyscript.py

