name: Test workflow

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hello
        run: docker run hello-world
